name: Test Go Code
on:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
        go-platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.go-platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...